name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: plugin
    attributes:
      label: Which plugin would this affect?
      description: Select the plugin or choose "New Plugin" for a new plugin request
      options:
        - New Plugin
        - General/Meta Repository
        - FugsOpusMVMZ
        - FugsOnlyOggMV
        - FugMasterVolume
        - FugsMultiTrackAudioEX
        - FugsChatBubbles
        - FugsYEP-GalvSpriteOffsetFix
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: rpg-maker-version
    attributes:
      label: Target RPG Maker Version
      description: Which version of RPG Maker should this support?
      options:
        - RPG Maker MV
        - RPG Maker MZ
        - Both
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternatives...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information...
    validations:
      required: false
